### ISSUE TITLE
[native-image] Vanilla project does not work with GraalVM 19.3.0

### ISSUE THREAD

**Issue by bjuretic** [micronaut-projects/micronaut-flyway#25]
Micronaut 1.2.8 (and 1.3.0.M2)
GraalVM 19.3.0.

```
implementation 'io.micronaut.configuration:micronaut-flyway'
```

Vanilla project created. 

```
$ native-image --no-server -cp build/libs/my-service-0.1-all.jar
```

```
$ ./my-service
13:12:23.677 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.micronaut.configuration.dbmigration.flyway.FlywayConfigurationProperties] could not be loaded: Error instantiating bean of type [io.micronaut.configuration.dbmigration.flyway.FlywayConfigurationProperties]: null
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.configuration.dbmigration.flyway.FlywayConfigurationProperties] could not be loaded: Error instantiating bean of type [io.micronaut.configuration.dbmigration.flyway.FlywayConfigurationProperties]: null
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1264)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:236)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2446)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:200)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
	at com.pencepay.webhook.Application.main(Application.kt:14)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.micronaut.configuration.dbmigration.flyway.FlywayConfigurationProperties]: null
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1626)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2307)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:1888)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1262)
	... 6 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:475)
	at org.flywaydb.core.internal.util.FeatureDetector.isSlf4jAvailable(FeatureDetector.java:96)
	at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:39)
	at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78)
	at org.flywaydb.core.internal.util.FeatureDetector.<clinit>(FeatureDetector.java:25)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:475)
	at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:35)
	at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.<clinit>(ClassicConfiguration.java:57)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:475)
	at org.flywaydb.core.api.configuration.FluentConfiguration.<init>(FluentConfiguration.java:46)
	at io.micronaut.configuration.dbmigration.flyway.FlywayConfigurationProperties.<init>(FlywayConfigurationProperties.java:48)
	at io.micronaut.configuration.dbmigration.flyway.$FlywayConfigurationPropertiesDefinition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:117)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:109)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1598)
	... 9 common frames omitted
Caused by: org.flywaydb.core.api.FlywayException: Unable to instantiate class org.flywaydb.core.internal.logging.javautil.JavaUtilLogCreator : org.flywaydb.core.internal.logging.javautil.JavaUtilLogCreator
	at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:63)
	at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:46)
	at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78)
	at org.flywaydb.core.internal.util.ClassUtils.<clinit>(ClassUtils.java:39)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	... 29 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.flywaydb.core.internal.logging.javautil.JavaUtilLogCreator
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.Class.forName(DynamicHub.java:1197)
	at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:61)
	... 34 common frames omitted
```

Do you know how to fix this? Problem seems to be in `Caused by: java.lang.ClassNotFoundException: org.flywaydb.core.internal.logging.javautil.JavaUtilLogCreator`

Adding it with `@TypeHint` to Application did not help.

**Comment by bjuretic** [comment]
So this can be fixed using something like https://github.com/barryku/karaf-flyway-demo/pull/1/commits/f04d3a95a491f7202c02a537ee740d89d71a844f  and then adding `LogFactory.setLogCreator(Slf4jLogCreator())` before Flyway is initialized (this should be added to micronaut-flyway), like in that commit.

But, then there is a new problem after a recompiled native executable is started: 

```
20:14:45.214 [pool-2-thread-1] INFO  i.m.c.d.f.AbstractFlywayMigration - Running migrations for database with qualifier [default]

....
Caused by: org.flywaydb.core.api.FlywayException: Unable to obtain inputstream for resource: org/flywaydb/core/internal/version.txt
```

This has something to do with which ClassLoader is used to retrieve version.txt

In any case micronaut-flyway does not work with GraalVM. I suggest taking all the solutions from Quarkus Flyway extension, as they have solved all the problems already with flyway running native.

**Comment by morki** [comment]
@ilopmar Please is Graal support on roadmap?

**Comment by ilopmar** [comment]
Adding the following `@TypeHint`:
```java
@TypeHint(typeNames = {
        "org.h2.Driver",
        "org.h2.mvstore.db.MVTableEngine",
        "org.flywaydb.core.internal.logging.javautil.JavaUtilLogCreator"}, // <--- This
        accessType = TypeHint.AccessType.ALL_PUBLIC
)
```

And declaring the static resouces in the `native-image.properties`

```properties
Args = -H:IncludeResources=logback.xml|application.yml|bootstrap.yml|org/flywaydb/core/internal/version.txt|org/flywaydb/core/internal/database/h2/createMetaDataTable.sql|databasemigrations/.* \
...
...
```

Makes it work with H2. We will need to declare all the sql files for all the databases.

```
$ ./mn-flyway-graal
13:27:30.800 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
13:27:30.803 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
13:27:30.803 [main] INFO  i.m.c.d.f.AbstractFlywayMigration - Running migrations for database with qualifier [default]
Apr 28, 2020 1:27:30 PM org.flywaydb.core.internal.license.VersionPrinter printVersionOnly
INFO: Flyway Community Edition 5.2.4 by Boxfuse
Apr 28, 2020 1:27:30 PM org.flywaydb.core.internal.database.DatabaseFactory createDatabase
INFO: Database: jdbc:h2:mem:devDb (H2 1.4)
Apr 28, 2020 1:27:30 PM org.flywaydb.core.internal.database.base.Database recommendFlywayUpgradeIfNecessary
WARNING: Flyway upgrade recommended: H2 1.4.199 is newer than this version of Flyway and support has not been tested.
Apr 28, 2020 1:27:30 PM org.flywaydb.core.internal.scanner.classpath.ClassPathScanner findResourceNames
WARNING: Unable to resolve location classpath:databasemigrations
Apr 28, 2020 1:27:30 PM org.flywaydb.core.internal.command.DbValidate validate
INFO: Successfully validated 0 migrations (execution time 00:00.000s)
Apr 28, 2020 1:27:30 PM org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory create
INFO: Creating Schema History table: "PUBLIC"."flyway_schema_history"
Apr 28, 2020 1:27:30 PM org.flywaydb.core.internal.command.DbMigrate migrateGroup
INFO: Current version of schema "PUBLIC": << Empty Schema >>
Apr 28, 2020 1:27:30 PM org.flywaydb.core.internal.command.DbMigrate logSummary
INFO: Schema "PUBLIC" is up to date. No migration necessary.
13:27:30.826 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 41ms. Server Running: http://localhost:8080
```

The problem as you can see is that it can't find the migrations on the classpath so I'll try to follow the same approach as in Quarkus explained here: https://github.com/micronaut-projects/micronaut-flyway/issues/12#issuecomment-570781125

**Comment by morki** [comment]
Thank you very much @ilopmar, it would be awesome. I can help with testing with mariadb and postgres, when it'll be done.

**Comment by morki** [comment]
@ilopmar any progress here please?

**Comment by ilopmar** [comment]
@morki sorry, I've been busy with other tasks. Unless something new and more important appears, I'll start working on this tomorrow or Wednesday.
