### ISSUE TITLE
Enabling flyway clean scema does not work with native image

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-flyway#340]
### Expected Behavior

Should work

### Actual Behaviour

Fails with:

```
Caused by: java.lang.ClassNotFoundException: org.flywaydb.core.internal.command.DbClean
        at java.lang.Class.forName(DynamicHub.java:1136)
        at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:57)
        ... 31 common frames omitted
```

### Steps To Reproduce

Use this config:

```yaml
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      clean-schema: true
```

### Environment Information

Any

### Version

3.7.0

**Comment by Rob-Francis** [comment]
I've been experiencing the same issue when building and running a Micronaut application as a native image.
Currently using the workaround of adding the following to `META-INF/native-image/reflect-config.json`.
```
[
{"name":"org.flywaydb.core.internal.command.DbClean",
  "queryAllPublicConstructors":true,
  "methods":[{"name":"<init>","parameterTypes":["org.flywaydb.core.internal.database.base.Database","org.flywaydb.core.internal.schemahistory.SchemaHistory","org.flywaydb.core.internal.database.base.Schema","org.flywaydb.core.internal.database.base.Schema[]","org.flywaydb.core.internal.callback.CallbackExecutor","org.flywaydb.core.api.configuration.Configuration"] }]}
]
```

**Comment by graemerocher** [comment]
Seems to work in Flyway 9
